package com.dallascollege.monopoly.enums

enum class ActionType {
    PAY_RENT, PURCHASE_PROPERTY, GO_TO_JAIL, PAY_BANK, BUY_HOUSE, BUY_HOTEL, SELL_HOUSE, SELL_HOTEL, MORTGAGE_PROPERTY, SURRENDER, GET_OUT_OF_JAIL, SKIP
}